version: '3.9'
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: balancehub
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    command: bash -lc "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/balancehub
      - SYNC_DATABASE_URL=postgresql+psycopg2://postgres:postgres@db:5432/balancehub
      - JWT_SECRET=dev_secret_change_me
      - WEBHOOK_SECRET_KEY=gfdmhghif38yrf9ew0jkf32
      - ENV=dev
      - DEBUG=true
      - CORS_ORIGINS=*
      - RATE_LIMIT=100/minute
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
